# Generated by Django 2.2 on 2019-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=255)),
                ('category', models.CharField(choices=[('Con', 'Conference'), ('Pres', 'Presentation'), ('Sem', 'Seminar')], max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('e_start_time', models.DateTimeField()),
                ('e_end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('registrants', models.BooleanField()),
                ('e_image', models.ImageField(upload_to='')),
                ('e_adult_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('e_child_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, choices=[('U', 'User'), ('A', 'Admin')], max_length=5)),
            ],
        ),
    ]
