# Generated by Django 2.2 on 2019-04-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190402_1633'),
        ('app', '0005_auto_20190402_1618'),
    ]

    operations = [
    ]
