# Generated by Django 2.1.7 on 2019-04-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190402_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Pres', 'Presentation'), ('Con', 'Conference'), ('Sem', 'Seminar')], max_length=4),
        ),
    ]
