# Generated by Django 2.1.7 on 2019-04-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190402_1811'),
        ('app', '0012_auto_20190402_1806'),
    ]

    operations = [
    ]
