# Generated by Django 2.2 on 2019-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190402_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Pres', 'Presentation'), ('Sem', 'Seminar'), ('Con', 'Conference')], max_length=4),
        ),
        migrations.AlterField(
            model_name='regform',
            name='adultQty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regform',
            name='childQty',
            field=models.IntegerField(),
        ),
    ]
