# Generated by Django 2.2 on 2019-04-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190402_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Con', 'Conference'), ('Pres', 'Presentation'), ('Sem', 'Seminar')], max_length=4),
        ),
    ]
