# Generated by Django 2.2 on 2019-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190403_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Pres', 'Presentation'), ('Con', 'Conference'), ('Sem', 'Seminar')], max_length=4),
        ),
    ]
