# Generated by Django 2.2 on 2019-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190403_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sem', 'Seminar'), ('Con', 'Conference'), ('Pres', 'Presentation')], max_length=4),
        ),
    ]
