# Generated by Django 2.2 on 2019-04-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190403_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sem', 'Seminar'), ('Pres', 'Presentation'), ('Con', 'Conference')], max_length=4),
        ),
    ]
