# Generated by Django 2.2 on 2019-04-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190403_1520'),
        ('app', '0016_auto_20190402_2006'),
    ]

    operations = [
    ]
