# Generated by Django 2.1.7 on 2019-04-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190403_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sem', 'Seminar'), ('Pres', 'Presentation'), ('Con', 'Conference')], max_length=4),
        ),
    ]
