# Generated by Django 2.1.7 on 2019-04-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190403_1606'),
        ('app', '0042_auto_20190403_1640'),
    ]

    operations = [
    ]
