# Generated by Django 2.2 on 2019-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20190403_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Pres', 'Presentation'), ('Con', 'Conference'), ('Sem', 'Seminar')], max_length=4),
        ),
    ]
