# Generated by Django 2.2 on 2019-04-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20190403_1914'),
        ('app', '0043_merge_20190403_1802'),
    ]

    operations = [
    ]
