# Generated by Django 2.2 on 2019-04-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20190403_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sem', 'Seminar'), ('Pres', 'Presentation'), ('Con', 'Conference')], max_length=4),
        ),
    ]
