# Generated by Django 2.2 on 2019-04-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20190403_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Con', 'Conference'), ('Sem', 'Seminar'), ('Pres', 'Presentation')], max_length=4),
        ),
    ]
